# Generated by Django 3.1.4 on 2020-12-30 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20201230_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='facilites',
            new_name='facilities',
        ),
    ]
