# Generated by Django 3.1.4 on 2021-01-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20201231_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='purpose',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
